{{- if .Values.https.enabled }}
{{- if not .Values.https.keystoreSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}-https
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-https" (include "geoserver.fullname" .)) }}
  {{- if $existingSecret }}
  # Preserve existing keystore password
  keystorePassword: {{ index $existingSecret.data "keystorePassword" }}
  {{- else }}
  # Generate new keystore password (32 characters, base64 encoded)
  keystorePassword: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  # Note: You need to manually add your keystore.jks file to this secret
  # Use: kubectl patch secret {{ include "geoserver.fullname" . }}-https -n {{ .Release.Namespace }} --patch='{"data":{"keystore.jks":"<base64-encoded-keystore>"}}'
{{- end }}
{{- end }}
