{{- if and .Values.https.enabled .Values.https.autoGenerateKeystore (not .Values.https.keystoreSecret) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: keystore-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: keystore-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - {{ include "geoserver.fullname" . }}-https
    {{- if .Values.https.keystoreGenerator.secretName }}
    - {{ .Values.https.keystoreGenerator.secretName }}
    {{- end }}
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: keystore-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
