{{- if and .Values.https.enabled .Values.https.autoGenerateKeystore (not .Values.https.keystoreSecret) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "geoserver.fullname" . }}-keystore-generator
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: keystore-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keystore-generator
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "geoserver.fullname" . }}-keystore-generator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: keystore-generator
        image: {{ .Values.https.keystoreGenerator.image.repository }}:{{ .Values.https.keystoreGenerator.image.tag }}
        imagePullPolicy: {{ .Values.https.keystoreGenerator.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        env:
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "geoserver.fullname" . }}-https-temp
              key: keystorePassword
        - name: DOMAIN_NAME
          value: {{ .Values.https.keystoreGenerator.domainName | quote }}
        - name: KEY_ALIAS
          value: {{ .Values.https.keyAlias | quote }}
        - name: KEYSTORE_PATH
          value: "/tmp/keystore.jks"
        - name: SECRET_NAME
          value: {{ include "geoserver.fullname" . }}-https
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: ORGANIZATION
          value: {{ .Values.https.keystoreGenerator.organization | quote }}
        - name: COUNTRY
          value: {{ .Values.https.keystoreGenerator.country | quote }}
        - name: VALIDITY_DAYS
          value: {{ .Values.https.keystoreGenerator.validityDays | quote }}
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: script-volume
          mountPath: /scripts
        command:
        - /bin/bash
        - /scripts/generate-keystore.sh
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: {{ include "geoserver.fullname" . }}-keystore-script
          defaultMode: 0755
{{- end }}
